name: ShopSystem
main: com.craftvn.shopsystem.ShopSystem
version: 1.0.0
api-version: '1.21'
author: CraftVN
depend: [Vault, PlayerPoints]

commands:
  shopcoin:
    description: Mở Shop Coin (Vault)
  shopgem:
    description: Mở Shop Gem (PlayerPoints)
  bando:
    description: Bán đồ lấy coin
